#Jekyll configuration
name: Define the Odds
description: chronicling my adventures in learning
url: "http://oddlyaware.github.io"
markdown: GFM
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
